export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';
export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG';
export const DANG_KY_ACTION = 'DANG_KY_ACTION';
export const GET_THONG_TIN_TK = 'GET_THONG_TIN_TK';
export const CAP_NHAP_THONG_TIN_TK = 'CAP_NHAP_THONG_TIN_TK';
export const GET_MA_LOAI_NGUOI_DUNG = 'GET_MA_LOAI_NGUOI_DUNG';
export const THONG_TIN_CAN_CAP_NHAP = 'THONG_TIN_CAN_CAP_NHAP';